{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.redth.netlift",
    "module": "netlift-gradle-plugin",
    "version": "0.1.0-alpha.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "netlift-gradle-plugin-0.1.0-alpha.8.jar",
          "url": "netlift-gradle-plugin-0.1.0-alpha.8.jar",
          "size": 201268,
          "sha512": "917c4bebb19886c38b42f41cc4cb6ee6008e7d0c8c99f5f86c1f289ca23bb9910d3af1fbc32260ef716a404d8e93f1d3389fb9df04f7bc9c23df0c9b8eb42a67",
          "sha256": "5ccfcaf0df92fb25eab84d8161765ef474bc5f624e225aba8ffa7c504589f03a",
          "sha1": "bc3c42994cf473a533bf4094f8ca35bfeb4b399d",
          "md5": "108bb68b8c8e544e8a4274325cc0f0f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "netlift-gradle-plugin-0.1.0-alpha.8.jar",
          "url": "netlift-gradle-plugin-0.1.0-alpha.8.jar",
          "size": 201268,
          "sha512": "917c4bebb19886c38b42f41cc4cb6ee6008e7d0c8c99f5f86c1f289ca23bb9910d3af1fbc32260ef716a404d8e93f1d3389fb9df04f7bc9c23df0c9b8eb42a67",
          "sha256": "5ccfcaf0df92fb25eab84d8161765ef474bc5f624e225aba8ffa7c504589f03a",
          "sha1": "bc3c42994cf473a533bf4094f8ca35bfeb4b399d",
          "md5": "108bb68b8c8e544e8a4274325cc0f0f2"
        }
      ]
    }
  ]
}
